name: video_downloader
description: A modern video downloader app for YouTube, Instagram, and TikTok
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  youtube_explode_dart: ^1.12.4
  path_provider: ^2.1.1
  dio: ^5.3.2
  permission_handler: ^10.4.3
  provider: ^6.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  video_player: ^2.7.0
  flutter_insta: ^1.0.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
